_posts/2016-12-21-the-base-two-apprenticeship.md
Per Caitlin, changed the link from Rachel's Twitter account to link to her website.
=> fix(blog-post): Change Rachel Krantz link from Twitter to website

src/util/graphql.js
- Add export for `toNodes` to GraphQL util
Closes #158.
=> fix(build): Fix missing toNodes issue

.prettierrc, gatsby-node.js, package-lock.json, package.json
- Configure Netlify to deploy the `gatsby-version` branch
- Configure `prettier` to format `gatsby-node.js` with ES5 trailing commas
- Add formatting settings to `.prettierrc`
Closes #126.
=> chore(build): setup continuous deployment

src/components/organisms/contact/ContactHeader.jsx
Added widths to LocationTagline and ScollButton
Although dealing with widths, may be related to known IE flexbox bug:
https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview
Closes #214 and #215
=> (fix) 214 Contact Us Text Center IE

src/components/molecules/GlobalNavigation.jsx, src/layouts/index.jsx
Closes #264 for good, hopefully.
Overflow: hidden wasn't working because a height needed to be designated. It is now.
=> #264 fix mobile nav no scroll

src/html.jsx
Errors pointed to Luxon - used fix found here: https://moment.github.io/luxon/docs/manual/install.html
=> fix(blog) Blog Link Fails IE11

src/components/molecules/GlobalNavigation.jsx, src/layouts/index.jsx
Moved noScroll toggle into its own const, included in both click handler functions so that toggle occurs before default action.
Closes #282
=> fix(nav): #282 Navigation noScroll issue

src/components/organisms/ContactUs.jsx, src/layouts/index.jsx
Updated overflow on page and on Contact Us wrapper to fix IE bug.
Closes #273
=> fix(site): Space After Navigation Link Clicked in IE

src/components/molecules/GlobalNavigation.jsx
I think this'll fix it: the blog link in the Global Nav now has a click handler.
Closes #298
=> fix(blog): Blog mobile no scroll

src/layouts/index.jsx
Added one more location string to the script that determines whether a page is a blog page. I suspect (and have seen on my own phone) that mobile Chrome adds a trailing slash on refresh.
Closes #297
=> fix(blog): Blog background color

src/components/organisms/Hero.jsx
Issue: The hero background has an aspect ratio such that it can't fully fit on smaller devices (when the width is set to 100vw). 
Fix: By increasing the height of the container to 110vh, the background will not be cut off anymore. 
Fallout: The Scroll Link got its position from the height of the Hero container, so that was forcing it off-screen also. I set the Scroll Link to be positioned based on the view height instead of the Hero height, which seems to fix it.
Closes #259
=> fix(hero): Hero background gets cut off on mobile.

_content/posts/2018-05-03-aurelia-async-routing.md
=> fix(blog-post): Aurelia Async Router edits

_content/posts/2013-08-23-startup-magnet-poetry.md, _content/posts/2015-05-13-regex-replace-with-groups.md, _content/posts/2015-06-01-shortcut-month.md, _content/posts/2015-12-30-jscs-intellij-setup.md, _content/posts/2016-05-25-a-google-io-experience.md, _content/posts/2017-01-03-apprenticeship-month-1.md, _content/posts/2017-02-08-mac-setup.md
Closes #354 
Note: The image issue is due to base2.io being https, and the imgur links being http.  I updated the links, it should work, but we won't know for sure until this is deployed.
=> fix(blog): Broken Blog Images and Links

package.json, src/util/style.js
Closes #375 
The background images were not displaying on Apple devices because our method of support detection for webp was determining that Safari supported webp (it does not).
Used webp support detection package instead.
=> Background Images Not Displaying in Mobile

src/components/organisms/jobs/JobsHeader.jsx
Went with the straightforward path of just using the png image rather
than trying the webp.
Closes #418
=> fix: ie11 image not appearing

package-lock.json, package.json, src/pages/index.jsx, src/util/globalStyles.js
* :rocket: Upgrade `styled-components`, `babel-plugin-styled-components`, and
`gatsby-plugin-styled-components`.
* :rotating_light: This upgrade now deprecates `injectGlobal` in favor
of the new API: `createGlobalStyle`.
See `src/util/globalStyles.js`for usage, or in the docs:
https://styled-components.com/docs/api#createglobalstyle
Closes: #395
=> chore(site): Upgrade `styled-components`

package-lock.json, package.json, src/components/molecules/GlobalNavigation.jsx, src/pages/index.jsx
* Add smooth scrolling package that applies to all anchor links
* Change top link to a #top anchor tag
note: the polyfill for this has a conflict with Gatsby SSR, so I'm importing the non-polyfilled script directly.  Browsers without support will stick to jump navigation instead of scroll.
closes #237
=> feat(site): Smooth scrolling on nav link

src/components/molecules/BlogHeader.jsx
Closes #374
IE11 has some irregular behavior with flexboxes that require explicitly setting the width sometimes.
Before:
After:
=> fix(site): Blog header compression on IE11

src/components/organisms/Hero.jsx
Close #486
I noticed at certain sizes the text overlaps the brighter area of the background and the contrast isn't the best, but I'm not sure what the best way to fix it would be or how much it really matters.
=> feat(site): Add mission statement

src/util/style.js
Close #477
The wrapper in the Clients section was intended to have a padding at the bottom where a linear gradient would sit. The padding was getting overwritten by the standard container styles, and then linear gradient was in the same space.
To fix this, I changed the common container styles to only set the left and right padding, which is I think what it was intended for.
=> fix(site): Fix "View Our Work" button

_content/posts/2013-11-30-link-roundup-2.md, _content/posts/2016-05-25-a-google-io-experience.md, src/components/molecules/YouTube.jsx, src/components/molecules/index.js, src/templates/post.jsx, src/util/templates.jsx
Close #287
There wasn't really anything to enable/fix here, I assume due to the recent MDX changes. I added a `YouTube` component that fills the available width while maintaining proper aspect ratio, and embedded existing YouTube videos where it makes sense.
=> feat(blog): Enable embedding iframes in blog posts.

gatsby-browser.js, package-lock.json, package.json, src/html.jsx
Close #393, Close #371
Most of the polyfills we need are taken care of by Babel, [Gatsby](https://www.gatsbyjs.org/docs/browser-support/), and BrowsersList. Other than that, `smooth-scroll` requires `CustomEvent` and `Element.closest`.
Tested in Safari (Mac/iOS), IE11, Firefox, and Chrome.
=> fix(site): Streamline polyfills

src/components/index.ts
Closes B2-64
Adjust the order of imports based on their dependent usage rather than
simply by alphabetical order.
=> chore: index import sort order

src/components/HomePage/HomeHero.tsx
Closes [B2-75](https://b2io.atlassian.net/browse/B2-75)
- adjusted padding to address header alignment on smaller screens
NOTES: 
- Discussed the implementation of these changes with Ashley, Tony, and Drew
**Next Steps**
<details>
<summary>mobile</summary>
</details>
<details>
<summary>tablet</summary>
</details>
<details>
<summary>desktop</summary>
</details>
=> adjust padding for HomeHero on smaller screens

src/components/IconCard.stories.tsx, src/components/IconCard.tsx, src/components/index.ts, src/theme/index.ts
[[B2-5](https://b2io.atlassian.net/browse/B2-5)]
- Create Icon Card component to take in an icon type, heading, and text.
Pages that use the Icon Card component:
<details>
<summary>Culture</summary>
<details>
<summary>Approach</summary>
<details>
<summary>Work</summary>
=> Create Icon Card component

src/components/Footer.tsx
1. Fix alignment issue of footer links in Safari (created a new styled-component based on Link and adjusted the line-height)
2. Set the font-style property of the ContactLink styled-component to normal instead of italic so it matches the Zeplin comp.
=> fix footer alignment in safari

src/components/WorkPage/FeaturedCaseStudyHero.tsx
Update the src path for the Paint a Photo image on the Work page. 
I tried using the full image with the bottom navigation but the aspect ratio was getting lost. I tried using `object-fit` but it would just crop the image to fit inside the div, so I just ended up using the `featured-case-study-1.png` img from the `HomePage` component. I mocked it up in a codepen but wasn't able to get much farther. Open to suggestions!
=> update src path for cse study img

.eslintrc, src/components/ApproachPage/HowWeEngage.tsx, src/components/ContactPage/ContactForm.tsx, src/components/Container.tsx, src/components/Footer.tsx, src/components/Header.tsx, src/components/PageHero.tsx
Card issue link: [b2-132](https://b2io.atlassian.net/browse/B2-132)
- Added a text-shadow style to the PageHero component
- All PageHero texts will now be easier to read when over an image.
Would you guys consider this best practice? Instead of adding the same style to 3 different pages, I just added the style once to the one shared component (PageHero).
=> b2-132 added text-shadow to pageHero comp

src/components/MobileMenu.tsx
Looks like the clamp in Global Styles had repercussions on the spacing for this menu nav. As this is a one-off situation, I just used a styled component fix to override the settings on `<a>` tags that kick in here on the mobile breakpoint.
Bug:
Also noticed a spacing discrepancy between the `ContactLink`s
=> Fixed mobile menu styling

src/components/HomePage/index.tsx, src/components/WorkPage/CaseStudyNav.tsx
Zeplin comp for reference:
📌 `CaseStudyNav` component is at the bottom of the homepage. I will remove once PR is approved!
Looking for feedback on this component since I feel like I over-engineered some things to get it looking like the designs 😬
📓 **A couple of notes:**
For the image overlay -- I had a little trouble getting it to work on both desktop and mobile so I just adjusted the image opacity which I think works better for readability, but open to feedback on recreating this!
On mobile, I positioned the text directly below the image since I had a bit of trouble getting this to work, but I do think it's better for readability.
=> B2 30 case study nav component

.eslintrc, next.config.js, src/pages/_app.tsx
This PR tackles cards:
https://github.com/b2io/base2.io/issues/690
https://github.com/b2io/base2.io/issues/721
🩹  workaround for old nextjs es lint bug,
https://github.com/vercel/next.js/issues/28971
Bug found in old version of next / eslint dependecies, disabling the rule is a temporary workaround. Blocked from building the app without the rule off. True fix is by updating dependencies which is its own task/pr/card. 
➖  deprecated prefetch src csp,
The Prefetch src CSP rule is deprecated and unrecognized by chromium/Firefox. Safe to delete.
🩹  workaround preload attribute on italic font link
App struggled to preload an italic font link. Workaround was to remove the preload attribute. No discernible performance impact without the preload.
* Note: If viewing the vercel live preview, there …
=> Cleaned up some console errors.

src/components/Card.tsx
- passed props to BasicCard in order to give children access to "as" prop and properly render as "li" elements
Before
After
=> 822: CardGrid accessibility issue

src/components/Card.tsx
passed props to ResultCard in order to give children access to "as" prop and properly render as "li" elements
Before
After
=> 824: ResultCard accessibility issue

src/components/Common/Card.tsx
- refactored ResultCard to reduce inline typography styling and prevent breakage
**Note**
The goal with this is not to make the styling match the designs but to prevent broken layouts and simplify the approach to typography until it can be addressed 
Resolves [826](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=51183468)
=> 826:  fix ResultCard typography 

src/components/Layouts/Header.tsx
- adjusted syntax and rule is now applied
**Test**
- run site locally or visit preview
- inspect Header 
- verify that "background-image" rule is valid and visually applied
Resolves [855](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=52557642)
=> 855: Header gradient not being applied

src/components/Common/QuotedImage.tsx, src/theme/typography.ts
- utilized existing h3 variant for quotation text
- adjusted styling
- removed quotationText variant
Before 
After 
Resolves [857](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=52565420)
=> 857: update sizing of quotation text

src/components/ServicesPage/OurServices.tsx
Closes #772 
I think the `Service` tag needs to be replaced with the Element tag from react-scroll. Since the warning only shows up in production, I'm not totally sure how to test this.
=> #772: Console log warning from react-scroll
