b2io/base2.io

index.html
=> fix(team): Remove Zack

_posts/2015-05-13-regex-replace-with-groups.md
@jonathanchris @mewdriller @jridenbaugh @nschubach 
Please proof read. I plan to push at 4pm
=> doc(blog): Regex Replace with Groups

_posts/2015-06-01-shortcut-month.md
@jonathanchris @mewdriller @nschubach @jridenbaugh @zeroverride 
Sorry that I couldn't get this out sooner. If you're available please proofread before 9pm tonight (within the next 30 min). If I don't hear anything by then I'm going to merge, deploy, and begin tweeting. 
This will be a daily occurrence throughout June.
=> doc(shortcuts): June 1st - Move windows

_posts/2015-06-02-shortcut-month.md
@zeroverride JP, do you want to proofread this one?
=> doc(shortcut): cursor movement

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): google doc search menus

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): ctrl+shift+v

_posts/2015-06-01-shortcut-month.md
@zeroverride Lock your machine because there's a JP in every office ;-)
=> doc(shortcut): win+l

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): win+d

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): ctrl+t, ctrl+w

_posts/2015-06-01-shortcut-month.md
ctrl+space, shift+space for spreadsheet column/row selection.
Also updated 6/7 to include ctrl+shift+t
=> doc(shortcut): ctrl+space

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): insert/delete spreadsheet columns

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): alt+tab

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): alt+arrow-keys

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): j & k

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): ctrl+r

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): win+e win+r

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): f2

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): ctrl+n

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): ctrl+f

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): win

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): ctrl+shift+n

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): ctrl+z

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): ctrl+shift+printScreen

_posts/2015-06-01-shortcut-month.md, assets/css/blog.css
Also update styles to indent ordered lists.
=> doc(shortcut): Gmail shortcuts

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): ctrl+enter

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): / (jump to search)

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): gmail bullets

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): Bookmarks

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): Slack channel selector

_posts/2015-06-01-shortcut-month.md
=> doc(shortcut): chrome dev tools

_posts/2015-06-01-shortcut-month.md
Finalize post with 1 last shortcut and a conclusion.
=> Shortcut 6 30

assets/js/default.js
=> fix(menu): collapse menu on link click

assets/css/default.css
Necessary? Not really. But I feel a little better.
Alpha order properties. 
Remove trailing whitespace. 
Remove 0's before decimals.
Trailing semicolons for all properties.
Closes: #58
=> chore(css): alpha order and clean up css

_posts/2015-12-30-jscs-intellij-setup.md
Various comma, possessive, and wording changes.
=> WIP: Grammatical adjustments

_config.yml, _posts/2015-05-13-regex-replace-with-groups.md, _posts/2015-12-30-jscs-intellij-setup.md
* new blog post on discs
* added jstevens to authors list
* fixed spelling issue on regex blog
=> doc(blog): JSCS and Web Storm

.gitignore, package.json
Update the project to use npm scripts for common tasks.
Closes #75
=> chore(build): simplify project tooling

_posts/2016-12-21-the-base-two-apprenticeship.md
Wording has slight changes (and photos!) from the original Google doc.
=> Apprenticeship blog post

.gitignore, _config.yml, _posts/2017-01-03-apprenticeship-month-1.md
I'm looking for feedback and edits on anything.
=> feat(blog-post): 2016 12 an apprenticeship not an internship

_posts/2017-10-13-quilting-with-css-grid.md, index.html
*WIP*
Markup and Conclusion sections are unfinished. 
Feedback welcome.
=> Knitting with CSS Grid post

index.html
For new *and* old sites.
Unformatted Doc: https://docs.google.com/document/d/1gBmGnr3ZK1-FCWHnhg3ifHcMNEofXqqNvF1HhZdA4fg/edit#
=> Updated Contact Us section with new text.

gatsby-browser.js, package-lock.json, package.json, src/components/atoms/Img.jsx, src/templates/post.jsx, src/util/helpers.js
- Use IntersectionObserver to defer loading in Img
- Use custom Img component in blog posts
- Add polyfills for IE11
Closes #160.
=> feat(perf): Lazy-load offscren images

gatsby-config.js, package-lock.json, package.json
Installed and configured Gatsby Google Analytics Plugin.
=> chore(page-analytics): add analytics plugin

src/components/atoms/A.jsx, src/components/atoms/Address.jsx, src/components/atoms/index.js, src/components/organisms/ContactForm.jsx, src/components/organisms/ContactInformation.jsx, src/components/organisms/index.js, src/html.jsx, src/layouts/index.jsx, src/pages/index.jsx, src/theme.js
Updated markup and styles to add contact information.
=> feature(contact-us): Display contact information

src/components/atoms/Button.jsx, src/components/atoms/form/FormField.jsx, src/components/atoms/form/Input.jsx, src/components/atoms/form/Label.jsx, src/components/atoms/form/TextField.jsx, src/components/atoms/form/Textarea.jsx, src/components/organisms/ContactForm.jsx, src/layouts/index.jsx, src/theme.js
=> feat(site) Contact Form Styles

_posts/2017-11-22-knitting-with-css-grid.md
=> hotfix(blog): Add rest end to knitting post

_posts/2018-01-04-pc-setup.md
I haven't ran this locally, so I'm not sure how the formatting looks on our page.
Any and all feedback is welcome. The best writing is re-writing.
=> feat(blog-post): PC Setup

.babelrc, .stylelintrc, package-lock.json, package.json, src/components/atoms/LI.jsx, src/components/atoms/OL.jsx, src/components/atoms/P.jsx, src/components/atoms/UL.jsx, src/components/atoms/form/Input.jsx, src/components/atoms/form/Textarea.jsx, src/components/atoms/headers/Header.jsx, src/components/atoms/headers/headings.jsx, src/components/molecules/DescriptiveList.jsx, src/components/organisms/Hero.jsx, src/theme.js
- Added browser list to `.babelrc` and `.stylelintrc`
- Is there a way to write this once and share it between? idk, help appreciated
- Added Stylelint to project
- Removed offending CSS, commented out rules where necessary 
- Overrode rules that we can't abide by due to styled-components
Closes #196
=> chore(browser-matrix): Support target browsers

src/components/atoms/form/Textarea.jsx
Added overflow:auto to remove scrollbar in IE
Closes #216
=> Added overflow:auto to Textarea

package.json
Adds CSS linting to the lint-staged process.
Closes #209
=> CSS Lint on commit

src/components/atoms/headers/headings.jsx, src/pages/thanks.jsx
- Added background and text styles
- Removed team list
Closes #187
=> feat(contact-us): Thank You page

src/components/molecules/GlobalNavigation.jsx
=> fix(nav): Navigation Misaligned in IE (#235)

_content/clients.json
=> #245 Edit JSON file for Client Section

_content/posts/2016-05-25-a-google-io-experience.md
Couldn't solve the underlying issue on #239, so I've changed the embeds to inline links (ignoring tweets for now as they're not as important IMO).
Checked other blog posts for video embeds, this seems to be the only one.
=> Replaced iframe embeds with links to videos.

src/components/molecules/GlobalNavigation.jsx
=> #253 Fix email button on mobile nav

src/components/molecules/GlobalNavigation.jsx
=> #251-Close Mobile Nav on Link Click

src/components/organisms/contact/ContactForm.jsx
=> 256 submit button mobile fix

src/components/molecules/ServiceList.jsx
Updated max-width and added width to service list items to fix issue in Edge
=> #252 Service section in Edge issue

src/components/molecules/GlobalNavigation.jsx
=> fix(nav) Fix Mobile Nav No Scroll

src/components/molecules/GlobalNavigation.jsx
=> fix(nav) Mobile Contact Buttons Safari Android

src/components/molecules/GlobalNavigation.jsx
Wrapped nav logo in link, styled accordingly.
=> feat(site): #270 Base Two Logo should function as Home Link

src/components/molecules/GlobalNavigation.jsx, src/layouts/index.jsx
Not sure what we want our process to be here, but these bug fixes are ready to ship.
=> Merge develop into master

src/components/molecules/ScrollLink.jsx, src/components/molecules/index.js, src/components/organisms/Hero.jsx, src/components/organisms/contact/ContactHeader.jsx
=> feat(hero): Transform Satellite into Scroll Button

_content/posts/2017-11-22-knitting-with-css-grid.md, _content/posts/2018-01-04-pc-setup.md
Please double-check that the dates in the meta match the dates in the file paths.
On the CSS Grid post, I added a text link to the CodePen since the embed doesn't currently work in our Gatsby setup (see #239).
Closes #296
=> fix(blog): Missing blog posts #296

src/components/molecules/GlobalNavigation.jsx, src/components/molecules/ServiceList.jsx, src/components/organisms/Clients.jsx, src/components/organisms/ContactUs.jsx, src/components/organisms/contact/ContactHeader.jsx, src/pages/index.jsx, src/theme.js
Well... that took less time than I thought it would.
Closes #286
=> feature(nav): Fix nav to top #286

src/components/atoms/form/Input.jsx, src/components/atoms/form/Label.jsx, src/components/atoms/form/TextField.jsx, src/components/organisms/contact/ContactForm.jsx, src/theme.js
=> Form usability

src/pages/jobs/index.jsx
=> story(jobs): Jobs Page

src/components/organisms/contact/ContactInformation.jsx
=> Add Join Our Team to Contact Info

package-lock.json, src/components/organisms/index.js, src/components/organisms/jobs/JobForm.jsx, src/components/organisms/jobs/index.js
Adds component for job form. Works for both apprenticeships and regular jobs. Still might need some styling work. The file upload certainly needs styling work,.
=> Create Job Form

_content/posts/2012-04-30-now-with-more-jekyll.md, _content/posts/2012-05-01-vagrants-and-chefs-and-librarians-oh-my.md, _content/posts/2012-11-30-seeding-with-progress.md, _content/posts/2013-08-23-startup-magnet-poetry.md, _content/posts/2013-10-18-karma-tests-circle-ci.md, _content/posts/2013-10-29-conditionally-mock-http-backend.md, _content/posts/2013-11-23-link-roundup-1.md, _content/posts/2013-11-30-link-roundup-2.md, _content/posts/2013-12-07-link-roundup-3.md, _content/posts/2013-12-14-link-roundup-4.md, _content/posts/2014-02-25-autocomplete-and-the-three-algorithms.md, _content/posts/2014-03-09-wireframes-for-developers.md, _content/posts/2014-03-14-using-multi-buildpacks-to-deploy-a-yeoman-bower-grunt-application-on-rails.md, _content/posts/2014-08-04-angular-rails-api-template.md, _content/posts/2015-05-06-git-configured.md, _content/posts/2015-05-13-regex-replace-with-groups.md, _content/posts/2015-06-01-shortcut-month.md, _content/posts/2015-12-30-jscs-intellij-setup.md, _content/posts/2016-05-25-a-google-io-experience.md, _content/posts/2017-01-03-apprenticeship-month-1.md, _content/posts/2017-02-08-mac-setup.md, _content/posts/2017-11-22-knitting-with-css-grid.md, _content/posts/2018-01-04-pc-setup.md, package-lock.json, package.json, src/components/atoms/Blockquote.jsx, src/templates/post.jsx
Closes #361 
*This PR does not include styling for code blocks included in post.  That will be addressed in a separate task.
=> task(blog): New Blog Post Body -- 358

src/components/organisms/contact/ContactHeader.jsx
Closes #376 
Also refactored to stateless functional component.
=> Contact Section Image Not Sizing

_content/posts/2013-11-23-link-roundup-1.md, _content/posts/2013-11-30-link-roundup-2.md, _content/posts/2013-12-07-link-roundup-3.md, _content/posts/2013-12-14-link-roundup-4.md, gatsby-config.js
=> fix: add excerpt terminator

gatsby-node.js, src/components/molecules/GlobalNavigation.jsx, src/components/organisms/Clients.jsx, src/components/organisms/contact/ContactInformation.jsx, src/pages/case-studies/index.jsx
- Add Work link
- Keep Clients link and add description
- Link to work from clients
- Change routes to be case-studies rather than caseStudies
Closes #384
=> feat: case study global nav

_content/jobs/01-full-stack.md, _content/jobs/02-front-end.md
Add GraphQL and change list formatting.
Closes #422
=> doc: formatting changes

_content/jobs/03-react.md
=> React job branch

_content/posts/2019-12-30-messing-up.md
=> feat(blog): Messing Up

src/components/organisms/Hero.jsx
Close #481 
* Increase `font-weight` on mission statement
* Decrease font size
* Make an almost imperceptible change to `font-shadow` to make it more readable against a bright background
[Small](https://user-images.githubusercontent.com/7218166/77191823-ed3a5480-6ab1-11ea-993c-bb2885c2a170.png)
[Less small](https://user-images.githubusercontent.com/7218166/77191855-fc210700-6ab1-11ea-9393-ddecfba61de0.png)
[Medium](https://user-images.githubusercontent.com/7218166/77191890-0b07b980-6ab2-11ea-90b5-61f8aeb8ecb4.png)
[Large](https://user-images.githubusercontent.com/7218166/77191922-1bb82f80-6ab2-11ea-9bc2-372b7c67cbab.png)
=> chore(site): Mission statement font tweaks

src/pages/blog/index.jsx
Close #457 
Add feature image support (back) to the blog list.
[Uploading BlogPostList.png…]()
=> fix(site): Blog Post Feature Images

src/util/style.js
closes #470 
adjusted the width for the medium screen width to account for the ipad pro.
=> 470 tablet screen spacing

package.json, src/components/molecules/TechnologiesList.jsx, src/components/organisms/Technologies.jsx, src/components/organisms/caseStudies/CaseStudyAside.jsx
Closes #456 
-Added react tooltip to the project
-Added the tooltip to CaseStudyAside.jsx
=> 456 technology tooltip

src/components/organisms/contact/ContactHeader.jsx, src/pages/index.jsx
Closes #495 - added alt tags and meta data
Added React-Helmet to Index to add meta tags, plus twitter open graph tags, facebook open graph tags.
Added  alt tags to images that need them.
=> Closes #495 - added alt tags and meta data

_content/caseStudies/04-dnv-gl-battery-xt.md, _content/posts/2019-12-30-messing-up.md, gatsby-config.js, src/components/SeoComponent.jsx, src/components/index.js, src/components/organisms/contact/ContactHeader.jsx, src/pages/index.jsx, src/templates/caseStudy.jsx, src/templates/post.jsx
Closes #497 
Closes #437 
Created a reusable SEO component to be used in Blog posts, and case studies for the purpose of including basic SEO information and open graph to display post info and images in social media sharing.
=> 497 seo component

_content/team.json
Updated my title on the home page, since it must have gotten overwritten at some point.
=> Mike update title

_content/team.json
Update Zach's title in the team.json to reflect recent promotion
Closes #501
=> Zach Promotion title change

_content/posts/2020-12-12-svelte-ssr.md, package-lock.json, package.json, src/pages/blog/index.jsx, src/util/prism-languages.js
- Add svelte and diff highlighting and make them work
- Add blog post for SSR in Svelte
- Add accompanying code repository (private for now) at https://github.com/b2io/svelte-ssr-demo
=> feat: svelte SSR blogpost

README.md
Closes [B2IO-52](https://b2io.atlassian.net/browse/B2IO-52)
=> Add design links to readme

README.md
Closes [B2-55](https://b2io.atlassian.net/browse/B2-55) #comment
Update readme to include development workflow instructions. This includes
- updates to nvm/node installation
- Jira usage
- branch creation
- PR creation
=> task: update readme to include dev workflow

_content/team.json
=> chore(team): Updated Team roles

.storybook/.babelrc
=> chore(storybook): add babelrc

.storybook/main.js, .storybook/preview.js, src/components/CTA.tsx, src/components/Header.tsx, src/components/Layout.tsx, src/components/MobileMenu.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/theme/typography.ts
- update typography variables to match the zeplin styleguide
- update the font variants
- update the app to use `rem`s instead of `px` and variables when possible
Closes [B2-66](https://b2io.atlassian.net/browse/B2-66)
=> task: create and use typography theming

.storybook/main.js, package-lock.json, package.json
Adds default axe core accessibility checks to storybook component view.
https://storybook.js.org/addons/@storybook/addon-a11y
https://github.com/dequelabs/axe-core
=> chore(storybook): a11y addon

src/components/Footer.tsx
A lot of typography changes happened while the footer was in flight.
These changes remove the manual styling that is no longer needed
=> chore: clean-up of redundant styling

src/components/HomePage/FeaturedCaseStudy.tsx
Closes [B2-80](https://b2io.atlassian.net/browse/B2-80)
Add sup tag to register symbol
=> Add sup tag to register symbol

package-lock.json, src/components/CulturePage/index.tsx, src/components/PageHero.tsx, src/pages/culture.tsx, src/pages/culture/index.tsx, src/theme/typography.ts
[B2-18](https://b2io.atlassian.net/browse/B2-18)
=> Add open positions text and CTA to Culture page

src/components/organisms/contact/ContactHeader.jsx, src/components/organisms/jobs/JobForm.jsx, src/components/organisms/jobs/JobsContent.jsx
Closes #583
Add Atlanta, GA and Jersey City, NJ to our list of locations.
=> task: add cities

src/components/CulturePage/OurTeam.tsx
Rearranged staff photos in order of title, then in order of seniority.
Except for me and Melissa, I didn't like her dangling off the edge there.
=> Rearranged staff photos, heirarchy then seniority

src/components/Layout.tsx
=> Fix page titles in Layout

src/components/HomePage/BuiltForResults.tsx
Update the _**Function. Form. ROI**_ text color to coral.
=> Fix: update small text color to coral

src/components/ContactPage/ContactForm.tsx, src/components/ContactPage/index.tsx
1. Fix autocomplete bug on contact form.
2. Update blurb on contact page -- remove the semicolon and state from the locations list so it reads better. 
Definitely looking for some feedback on the copy for that blurb on the contact page!
=> WIP: update contact page blurb and fix autofill

src/components/HomePage/HomeHero.tsx, src/components/HomePage/index.tsx, src/components/Layout.tsx
=> Shift HomeHero to top of the screen

src/components/HomePage/DesignedForHumans.tsx
Adjust hero text breakpoint so that it starts to stack at a smaller breakpoint
=> Fix: adjust bp for hero text

src/components/BlogPage/index.tsx, src/components/CareersPage/index.tsx, src/components/WorkPage/index.tsx
Add SEO description tags for Careers, Blog and Work pages. Looking for feedback on the copy I used, especially for Blog!
=> WIP: Add seo tags for careers/blog/work pages

src/components/Footer.tsx
Closes [B2-63](https://b2io.atlassian.net/browse/B2-63)
- Add animation to footer white line
- Add "Lets talk" link component
=> Add animation to footer text on scroll and add color

src/components/PageHero.tsx
Added a contrast filter so that the Page Hero text has more contrast and is easier to read.
=> Added contrast filter

.vscode/settings.json, lib/gtag.js, src/pages/_app.tsx
This is a DRAFT PR, I am unable to really text if it's working until these changes are deployed. I'm hoping that someone has an idea as to how to stage this for testing?
Please DM Kate for the `.env.local` Google Analytics variable.
=> Google analytics g4

.eslintrc, lib/gtag.js, src/components/ContactPage/index.tsx, src/components/CulturePage/index.tsx, src/components/Layout.tsx, src/pages/_app.tsx
- implemented approach recommended by eslint docs for handling usage of emotion css with native elements 
- https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unknown-property.md
- noticed issue with google analytics in production and suppressed code for GA to be addressed in another task
- https://b2io.atlassian.net/jira/software/projects/B2/boards/7?selectedIssue=B2-195
=> update eslintrc to handle emotion css

src/components/BatteryXTPage/index.tsx, src/components/CaseStudy/CaseStudyBottomNav.tsx, src/components/CaseStudy/navProps.ts, src/components/ColorSnapVisualizerPage/index.tsx, src/components/NetJetsPage/index.tsx, src/components/ScopeBuilderPage/index.tsx
=> Revert "Case Study Bottom Nav"

framer.d.ts, package-lock.json, package.json, src/components/Card.tsx, src/components/CulturePage/OurTeam.tsx, src/components/Header.tsx, src/components/Layout.tsx, src/components/PageHero.tsx
- added priority prop to PageHero Next Image 
resolves [759](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=47242201)
=> 759: fix console warning for PageHero Next Image

src/pages/_app.tsx
removed motion.div from app.tsx as animation values are being passed in the Layout component and it appears to resolve the issue
**Test**
- run locally and verify that the home page does not double load
resolves [771](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=48110836)
=> 771: fix double animation load on home screen

src/components/WorkPage/FeaturedCaseStudyHero.tsx
[closes](https://github.com/b2io/base2.io/issues/765)
Before:
After:
=> B2 765 Make Registration mark smaller

package-lock.json, src/components/CaseStudy/CaseStudyBottomNav.tsx
[closes](https://github.com/b2io/base2.io/issues/781)
=> fix: One case study unseen error

package-lock.json, src/components/Card.tsx, src/components/List.tsx, src/components/index.ts, src/theme/general.ts
[closes](https://github.com/b2io/base2.io/issues/770)
=> b2 770 UL global style theme

src/components/ContactPage/ContactForm.tsx, src/components/ContactPage/index.tsx, src/components/Footer.tsx
removed references to address in Footer and Contact page
resolves [806](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=50151688)
=> 806: remove references to address 

src/components/CulturePage/OurTeam.tsx
=> update Culture page

src/components/CaseStudy/CaseStudyHero.tsx, src/components/CaseStudy/CaseStudySummaryPane.tsx, src/components/ColorSnapVisualizerPage/index.tsx, src/components/Common/TrademarkSymbol.tsx, src/components/CulturePage/OurTeam.tsx, src/components/HomePage/FeaturedCaseStudy.tsx, src/components/Layouts/Footer.tsx, src/components/Layouts/MobileMenu.tsx, src/components/NetJetsPage/index.tsx, src/components/ServicesPage/OurServices.tsx, src/components/WorkPage/CaseStudyPreview.tsx, src/components/WorkPage/FeaturedCaseStudyHero.tsx, src/components/index.ts, src/theme/typography.ts
Removed numerous instances of inline typography styling to allow for global approach to typography and unify styling across the site
resolves [843](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=51519546)
=> 843: cleanup inlined typography styling

src/components/Layouts/MobileMenu.tsx
- adjust spacing to fix breaking
=> 848: mobile nav spacing

src/components/CaseStudy/CaseStudyBottomNav.tsx
- adjusted font variant and styling to prevent responsive breaking 
Resolves [807](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=50168219) and [808](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=50168469) 
**Note**
The goal is no longer to align exactly with the design but rather to fix broken responsiveness and move towards updates to global typography
=> 807 and 808: fix CaseStudyBottom nav broken text and layout

src/components/CaseStudy/CaseStudyBottomNav.tsx, src/components/CaseStudy/CaseStudyIntroContentPane.tsx, src/components/CaseStudy/CaseStudyResultsPane.tsx
- updated CaseStudyBottomNav text link variant
- noticed inconsistent layout and updated case study pages to align with other pages
- adjusted spacing after removal of tech icons
- reduced CaseStudyResultsPane text max-length to improve readability
Resolves [754](https://github.com/orgs/b2io/projects/15/views/1?pane=issue&itemId=47207781)
=> 754: Improve CaseStudy layout consistency and copy readability

src/components/ApproachPage/HowWeEngage.tsx, src/components/Common/Link.tsx, src/components/ContactPage/ContactForm.tsx, src/components/HomePage/BuiltForResults.tsx, src/components/HomePage/DesignedForHumans.tsx, src/components/HomePage/FeaturedCaseStudy.tsx, src/components/HomePage/FueledByCuriosity.tsx, src/components/Layouts/Footer.tsx, src/components/ServicesPage/EstimationForm.tsx, src/theme/typography.ts
=> Chore-870: Add CTA to Section on Homepage and Better CTA titles
